### ISSUE TITLE
Templates that trip kcompiler

### ISSUE THREAD

**Issue by vkz** [vkz/bemhtml-syntax#22]
Is it ok to throw error or do we want some compiler magic to handle these?
- Problem is with non-standard args to `applyCtx`: 

``` js
block dropdown-menu {
    elem menu, default: {
        applyCtx(this._inDropdownMenu = true, {
            block: 'bla'
        });
    }
}
```
- Problem with computed prop in the arg to `applyNext`:

``` js
block button, mod round yes {
    default: applyNext(
      this.ctx.mods['only-icon'] = 'bla'
   )
}
```

^^ @veged @arikon @tadatuta

**Comment by tadatuta** [comment]
I think we need warning for the first case.

And as for second isn't it the same as

``` js
block('button').mod('round', 'yes').def()(function() {
    return applyNext({ "ctx.mods['only-icon']": 'bla' });
});
```

?
